defaults: &defaults
  app_name: "fc"
  domain: "http://fc.dev"    
  facebook_app_id: 
  facebook_secret: 
  hipchat_token: 
  hipchat_room_name: 
  admin_emails: 
    - ""
  google_analytics_key: ""
  default_logo_url: "/logo.png"
  email_sender: ""

jerrylocal:
  <<: *defaults

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
